"""Protocol interfaces for service decoupling."""
from typing import Protocol, Any, Callable, Awaitable, Optional


class ER2Port(Protocol):
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def send_audio(self, pcm_data: bytes) -> None: ...
    async def send_text(self, text: str) -> None: ...
    async def send_heartbeat(self, text: str) -> None: ...
    async def send_tool_response(self, responses: list) -> None: ...
    async def receive_loop(self) -> None: ...
    def set_tool_call_handler(self, handler: Callable) -> None: ...
    def set_block_interceptor(self, interceptor: Callable) -> None: ...


class MotionPort(Protocol):
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def generate(self, text: str, guidance_param: float = 3.0) -> dict: ...
    async def health_check(self) -> dict: ...
    async def is_available(self) -> bool: ...


class OSCPort(Protocol):
    def connect(self) -> None: ...
    async def play_motion(self, motion_data: dict) -> None: ...
    def stop(self) -> None: ...
    def send_idle_pose(self) -> None: ...


class AudioPort(Protocol):
    def set_callbacks(self, on_speech_start, on_speech_end, on_audio_chunk) -> None: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def play_audio(self, pcm_data: bytes) -> None: ...
    def stop_playback(self) -> None: ...


class TTSPort(Protocol):
    async def synthesize(self, text: str, emotion: str = "neutral", speech_rate: str = "normal") -> str: ...
    def clear_queue(self) -> None: ...
    async def get_next_audio(self) -> Optional[bytes]: ...


class DispatcherPort(Protocol):
    async def handle_tool_call(self, tool_call) -> list: ...
    async def cancel_pending(self, cancelled_ids: list) -> None: ...
    def get_state_summary(self) -> str: ...
