"""Protocol interfaces for service decoupling.

实现类显式继承对应 Protocol（如 ``class ER2Client(ER2Port)``），
同时支持静态类型检查（mypy/pyright）与运行时验证
（``isinstance(obj, ER2Port)``，因标有 @runtime_checkable）。
"""
from typing import Protocol, Any, Callable, Awaitable, Optional, runtime_checkable


@runtime_checkable
class ER2Port(Protocol):
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def send_audio(self, pcm_data: bytes) -> None: ...
    async def send_text(self, text: str) -> None: ...
    async def send_heartbeat(self, text: str) -> None: ...
    async def send_tool_response(self, responses: list) -> None: ...
    async def receive_loop(self) -> None: ...
    def set_tool_call_handler(self, handler: Callable) -> None: ...
    def set_block_interceptor(self, interceptor: Callable) -> None: ...


@runtime_checkable
class MotionPort(Protocol):
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def generate(self, text: str, guidance_param: float = 3.0) -> dict: ...
    async def health_check(self) -> dict: ...
    async def is_available(self) -> bool: ...
    @staticmethod
    def format_prompt(action: str, duration_seconds: float = 2.0) -> str: ...


@runtime_checkable
class OSCPort(Protocol):
    def connect(self) -> None: ...
    async def play_motion(self, motion_data: dict) -> None: ...
    def stop(self) -> None: ...
    def send_idle_pose(self) -> None: ...


@runtime_checkable
class AudioPort(Protocol):
    def set_callbacks(self, on_speech_start, on_speech_end, on_audio_chunk) -> None: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def play_audio(self, pcm_data: bytes) -> None: ...
    def stop_playback(self) -> None: ...


@runtime_checkable
class TTSPort(Protocol):
    async def synthesize(self, text: str, emotion: str = "neutral", speech_rate: str = "normal") -> str: ...
    def clear_queue(self) -> None: ...
    async def get_next_audio(self) -> Optional[bytes]: ...


@runtime_checkable
class DispatcherPort(Protocol):
    async def handle_tool_call(self, tool_call) -> list: ...
    async def cancel_pending(self, cancelled_ids: list) -> None: ...
    def get_state_summary(self) -> str: ...
